-- Schema for institute_db
-- Generated by Antigravity

-- 1. Roles
-- Stores the different roles available in the system (e.g., Admin, Teacher, Student)
CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Usuarios
-- Stores user information and links to a role
CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL, -- Should store hashed passwords
    rol_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Funciones
-- Represents modules or features of the system (e.g., 'Students', 'Grades', 'Reports')
CREATE TABLE funciones (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Acciones
-- Represents specific actions that can be performed (e.g., 'Create', 'Read', 'Update', 'Delete')
CREATE TABLE acciones (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE, -- e.g., 'crear', 'leer', 'editar', 'eliminar'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Permisos
-- Defines valid combinations of Functions and Actions (e.g., 'Can Read Students')
CREATE TABLE permisos (
    id SERIAL PRIMARY KEY,
    funcion_id INTEGER NOT NULL REFERENCES funciones(id) ON DELETE CASCADE,
    accion_id INTEGER NOT NULL REFERENCES acciones(id) ON DELETE CASCADE,
    UNIQUE(funcion_id, accion_id) -- Prevent duplicate permissions
);

-- 6. Rol_Permisos
-- Assigns specific permissions to roles (RBAC core)
CREATE TABLE rol_permisos (
    rol_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permiso_id INTEGER NOT NULL REFERENCES permisos(id) ON DELETE CASCADE,
    PRIMARY KEY (rol_id, permiso_id)
);


-- 7. Campus
-- Physical locations of the institute
CREATE TABLE campus (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    direccion VARCHAR(255),
    celular VARCHAR(20)
);

-- 8. Estudiantes
-- Student information
CREATE TABLE estudiantes (
    id SERIAL PRIMARY KEY,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    direccion VARCHAR(255),
    correo VARCHAR(150) UNIQUE,
    celular VARCHAR(20),
    campus_id INTEGER REFERENCES campus(id),
    usuario_id INTEGER REFERENCES usuarios(id), -- User who created the record
    sexo VARCHAR(20),
    fecha_nacimiento DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. Gestion
-- Academic Periods (e.g., 1-2024)
CREATE TABLE gestion (
    id SERIAL PRIMARY KEY,
    nro INTEGER NOT NULL,
    anio INTEGER NOT NULL,
    UNIQUE(nro, anio)
);

-- 10. Estudiante_Gestion
-- Enrollment records linking students to academic periods
CREATE TABLE estudiante_gestion (
    id SERIAL PRIMARY KEY,
    estudiante_id INTEGER REFERENCES estudiantes(id) ON DELETE CASCADE,
    gestion_id INTEGER REFERENCES gestion(id) ON DELETE RESTRICT,
    UNIQUE(estudiante_id, gestion_id)
);

-- 11. Parentesco
-- Relationship types (e.g., Father, Mother, Guardian)
CREATE TABLE parentesco (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

-- 12. Responsables
-- Guardians or responsible parties for students
CREATE TABLE responsables (
    id SERIAL PRIMARY KEY,
    estudiante_id INTEGER REFERENCES estudiantes(id) ON DELETE CASCADE,
    parentesco_id INTEGER REFERENCES parentesco(id),
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    direccion VARCHAR(255),
    correo VARCHAR(150),
    celular VARCHAR(20)
);

-- Indexes for performance
CREATE INDEX idx_usuarios_correo ON usuarios(correo);
CREATE INDEX idx_usuarios_rol ON usuarios(rol_id);
CREATE INDEX idx_estudiantes_campus ON estudiantes(campus_id);
CREATE INDEX idx_estudiantes_usuario ON estudiantes(usuario_id);
CREATE INDEX idx_estudiante_gestion_estudiante ON estudiante_gestion(estudiante_id);
CREATE INDEX idx_estudiante_gestion_gestion ON estudiante_gestion(gestion_id);
CREATE INDEX idx_responsables_estudiante ON responsables(estudiante_id);
